// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;

public class CartTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cart() {
    driver.get("https://www.rokomari.com/book");
    driver.manage().window().setSize(new Dimension(1449, 776));
    driver.findElement(By.cssSelector("#js--entry-popup .ion-close-round")).click();
 
    // Wait for the entry popup to disappear
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
    wait.until(ExpectedConditions.invisibilityOfElementLocated(By.id("js--entry-popup")));

    driver.findElement(By.id("js--search")).click();
    driver.findElement(By.id("js--search")).sendKeys("Net Pencil Bag");
    driver.findElement(By.id("js--search")).sendKeys(Keys.ENTER);
    
    
//    WebDriverWait wait1 = new WebDriverWait(driver, Duration.ofSeconds(10));
//    WebElement cartButton = wait1.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".cart-btn")));
//    cartButton.click();

    
    {
      WebElement element = driver.findElement(By.cssSelector(".w-100"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    js.executeScript("window.scrollTo(0,30)");
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    
    //WebDriverWait wait1 = new WebDriverWait(driver, Duration.ofSeconds(10));
    
    
    driver.findElement(By.cssSelector(".cart-btn")).click();
    driver.findElement(By.id("cart-icon")).click();
    driver.findElement(By.cssSelector(".icon-trash")).click();
    driver.findElement(By.cssSelector(".btn-remove-yes")).click();
    {
      WebElement element = driver.findElement(By.id("js--btn-minus-290312"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
